### DISCUSSION TITLE
New breaking change rule: Reducing maximum values for int parameters

### DISCUSSION THREAD

**Discussion by savage-alex** [opticdev/optic#1264] [Built-in Rulesets]
Please could we get a new rule added that reports when someone reduces an existing parameter maximum value down

Example of someone reducing the max value of a query parameter for pagination limits
```
      - name: limit
        in: query
        description: The maximum number of items to return for this call. The call also returns a token that you can specify in a subsequent call to get the next set of results.
        required: false
        style: form
        explode: true
        schema:
          maximum: 100
          minimum: 5
          type: integer
          format: int32
          default: 20
        example: 100
```
```
      - name: limit
        in: query
        description: The maximum number of items to return for this call. The call also returns a token that you can specify in a subsequent call to get the next set of results.
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 5
          type: integer
          format: int32
          default: 20
        example: 100
```
