### DISCUSSION TITLE
Is adding range information to an OpenAPI a breaking change?

### DISCUSSION THREAD

**Discussion by savage-alex** [opticdev/optic#1266] [Built-in Rulesets]
Strings, Ints and Numbers have range information describing their either max and min length or values and increments.

Would we consider adding these to be a potential breaking change? 

Assumption is normally its adding detail but what if there was no limit previously and now you are enforcing one?

String example (query param)
```
- name: manufacturerName
          in: query
          description: Car manufacture or brand name.
          schema:
            type: string
            minLength: 0
            maxLength: 100
            default: ""
          example: "audi"
```

Number example (query param)
```
- name: orderValueGreaterThan
          description: A filter on the list to return only orders with a value greater than a provided value. Allows up to 2 decimal places.
          required: false
          in: query
          schema:
            type: number
            format: double
            multipleOf: 0.01
            minimum: 0
            maximum: 100000000
          example: 100.99
```

Integer example (query param)
```
- name: offset
          in: query
          description: |
            The offset number from where the items should be listed. 
            Not including an offset will default to the first items in the list.
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 100000000
            default: 0
          example: 10
```
