### DISCUSSION TITLE
Breaking change: Changing the number of allowed items in an array

### DISCUSSION THREAD

**Discussion by savage-alex** [opticdev/optic#1268] [Built-in Rulesets]
Given the following parameter
```
- name: color
        in: query
        description: Color of the car. Its possible to filter on up to 5 colors at a time.
        required: false
        style: form
        explode: true
        schema:
          maxLength: 100
          minLength: 0
          maxItems: 10
          minItems: 0
          type: array
          items:
            type: string
            enum:
            - Black
            - Blue
            - Red
            - Silver
            - Green
            - Yellow
        example:
        - Blue
```

If the max or min items are changed this could be a breaking change
