### ISSUE TITLE
We should be lint-failing on $ref with siblings 

### ISSUE THREAD

**Issue by acunniffe** [opticdev/optic#1804]
**Describe the bug**
Optic is not failing when linting specs that have `$ref` and sibling properties specified: 

```yaml
field:
  $ref: ...
  type: object
```

The values are all getting merged. This happens at the dereference stage for some reason. The validation schema is working on a dereferenced spec, so it never sees a $ref. 

**Expected behavior**
Should fail when linting

**Screenshots**

**Details (please complete the following information):**
 - OS and version: [e.g. Mac OS 13.1]
 - Optic version: [e.g. v0.37.1]
 - NodeJS version: [e.g. 18.0.0]

**Additional context**

**Comment by niclim** [comment]
Additionally, we should detect things like:
```yml
schema:
  type: object
  oneOf / allOf / anyOf:...
```

This will cause similar issues
