### ISSUE TITLE
Output the same error 15 times instead of once

### ISSUE THREAD

**Issue by gabsong** [opticdev/optic#1832]
**Describe the bug**
Looks like a bug where if an unused component is found, it prints as many times as there are schemas. If I have 15 schemas and 1 is not found, the error prints 14 times. Tested by removing schemas from the spec file, and the output was proportionally reduced.

Example.

With `spectral`, I have the following output:
```text
~/home/repo/openapi/spec.v1.json
  86:16  warning  oas3-unused-component  Potentially unused component has been detected.  components.schemas.Health

... more warnings
```

With `optic`, I have the lines 3-5 repeating 14 times (after "FAIL Specification"):
```text
 FAIL  Specification

requirement rule: Spectral always rule
      x Error code: oas3-unused-component: Potentially unused component has been detected.
      at ~/home/repo/openapi/spec.v1.json:1:0

... more errors, i.e. operation-tag-defined errors
```

**To Reproduce**
1. Use the following **optic.dev.yml** and **spectral.yml** files
```yaml
ruleset:
  - breaking-changes:
      exclude_operations_with_extension: "x-draft"
  - spectral:
      always:
        - spectral.yml
```

```yaml
extends: "spectral:oas"
rules:
  oas3-unused-component: warn
```

2. Run `npx optic lint openapi/spec.v1.json`
3. See error

**Expected behavior**
Trying to understand why the output from spectral and optic are not matching.

**Details (please complete the following information):**
 - OS and version: MacOS 13.2.1
 - Optic version: 0.42.4
 - NodeJS version: 16.17.0
