### ISSUE TITLE
Feedback from bad server start does not make sense

### ISSUE THREAD

**Issue by acunniffe** [opticdev/optic#2188]
I'm trying to walk through the new capture story the same way a user might. Our errors are not making it easy to fix common issues

**when given it a command that does not run**

expect: 
"Waiting for server to start...."
"Server did not start...exiting. Check your command"

actual:
for some reason it tries to run the request

![Image](https://user-images.githubusercontent.com/5900338/258150665-fa184ac6-1640-4e2d-94d0-8cd79addc682.jpg)

**when you give it a command that starts a server, but it's on the wrong port**

expect:
"Waiting for server to start...."
"Server did not start on http://localhost:8080 after 10 seconds....exiting. Check your command"

![Image](https://user-images.githubusercontent.com/5900338/258151475-9ee21553-88f6-4544-8b8c-231cb9bddd13.jpg)

**Comment by notnmeyer** [comment]
paste/link your optic.yml please, pretty sure i know what's up with the first situation

**Comment by acunniffe** [comment]
```
capture:
  openapi.yml:
    server:
      # The command to run your server.
      # Optional: If omitted, Optic assumes the server is running or started elsewhere.
      command: npm run not-real
      # The url where your server can be reached once running.
      # Required: Can be overridden with '--server-override'.
      url: http://localhost:8080
      # A readiness endpoint for Optic to validate before sending requests.
      # Optional: If omitted, perform no readiness checking.

```
