### ISSUE TITLE
Follow up on #39 - publish to html

### ISSUE THREAD

**Issue by mikkelking** [opticdev/optic#244]
I am trying to follow the advice in #39 

```
   start:
     command: npm run start
     baseUrl: http://localhost:3700
   publish:
     oas: |
       widdershins {{{OAS_PATH}}} -o /tmp/api.md
       shins --inline -o ../doc/index.html /tmp/api.md
```
But this doesn't work for me. 

` ›   Error: command publish not found`

I can run these command from the command line, and I could create an npm script for them. I have tried a few combinations, including taking out the pipe after `oas:`, but nothing seems to work
