### ISSUE TITLE
Compatibility check: [error] request property oneOf schema did not overlap with the previous schema.

### ISSUE THREAD

**Issue by devova** [opticdev/optic#2836]
**Describe the bug**
I'm getting strange compatibility check: 
```
[error] request property oneOf schema did not overlap with the previous schema.
oneOf/0/property2.items/currency: required property was added,
oneOf/0/property2.items/amount: required property was added

Prevent expanded in request union types
```

**To Reproduce**
1. There was request schema
```
    TestSchema:
      type: object
      properties:
        property1:
          type: integer
      required:
        - property1
```
`TestSchema` is **oneOf** request bodies of a POST request
2. added a new _optional_ field `property2`, so the final schema looks like
```
    TestSchema:
      type: object
      properties:
        property1:
          type: integer
        property2:
          type: array
          default: []
          items:
            type: object
            properties:
              currency:
                type: string
              amount:
                type: integer
            required:
              - currency
              - amount
      required:
        - property1
```
4. Run `optic diff spec.yaml --base main --check`
5. See error

**Expected behavior**
I have added an optional empty list. So no error appears

**Screenshots**

**Details (please complete the following information):**
- CI web report [here](https://app.useoptic.com/organizations/af3e4ebd-4bbc-489f-96fe-c0b2bb22ba40/apis/7nd9n876p8sB-woBMq_D5/runs/RAhctz5LLOhXI8gvN_GmT). Hope you have access to it.
