### ISSUE TITLE
Generated OpenAPI spec doesn't use endpoint names, uses random string instead

### ISSUE THREAD

**Issue by ViRb3** [opticdev/optic#304]
When documenting my endpoints in Optic, I give them meaningful names like:
![image](https://user-images.githubusercontent.com/2650170/89718042-02a61180-d9b4-11ea-901c-83263a64855c.png)

Then I run `api generate:oas --yaml`, and in the generated spec, I can only find:
```yaml
paths:
 '/{apiVersion}/client_config':
  get:
   operationId: request_rkydO6Sol8
```

There's no trace of the readable name I gave it in Optic. This becomes a particular issue if I try to generate code, as it will use the `operationId` as method name. Is this a bug?
