### ISSUE TITLE
Processes will time out `api check` if they take longer than 25 seconds to start

### ISSUE THREAD

**Issue by LouManglass** [opticdev/optic#349]
If a process takes more than 25 seconds to start (the timeout for Optic checks) the Optic check will fail as it won't be able to reach anything on that port. This may be the intended behavior of a project (slow startup) but check will have no way to validate the configuration.

## Workaround

If all other checks pass, bypass the check with `api run <task>` instead. The run command will work, though the target application will need to start before traffic can be meaningfully observed. If startup is slow, please wait for the application to be fully initialized and ready for traffic.

## Reproduction

Reproduces 100% of the time on MacOS 10.15 though it's a timing issue, not an environment issue, and should generally reproduce. 

Reproduction `optic.yml` tasks below to demonstrate:

`optic.yml`
```  yaml
tasks:
  sleepy:
    command: sleep 30 && nc -l $OPTIC_API_PORT # 30 second sleep will fail
    baseUrl: http://localhost:3001
  awake:
    command: sleep 5 && nc -l $OPTIC_API_PORT # 5 second sleep will work
    baseUrl: http://localhost:3001
```

`api check awake`
``` bash
[optic] Testing task awake

Your command: sleep 5 && nc -l $OPTIC_API_PORT
  ✔ Starts a long running process (your API)
  ✔ On the host Optic assigns it $OPTIC_API_HOST (current: localhost)
  ✔ On the port Optic assigns it $OPTIC_API_PORT (current: 3399)

Given this inboundUrl: undefined
  ✔ Optic proxy is able to start its proxy here localhost:3001

[optic] All Passed! This task is setup properly. Nice work!
```

`api run sleepy`
```
[optic] Testing task sleepy

Your command: sleep 30 && nc -l $OPTIC_API_PORT
  ✔ Starts a long running process (your API)
  ✔ On the host Optic assigns it $OPTIC_API_HOST (current: localhost)
  ✖ On the port Optic assigns it $OPTIC_API_PORT (current: 3429)
    → Your command did not start the API on $OPTIC_API_PORT after 25 seconds

Given this inboundUrl: undefined
  ✔ Optic proxy is able to start its proxy here localhost:3001

[optic] Some checks failed. Steps to fix can be found here: useoptic.com/docs/check-fail
```
