### ISSUE TITLE
Does optic supports Python fastapi?

### ISSUE THREAD

**Issue by Sharathmk99** [opticdev/optic#72]
Hi Team,

Its very interesting project towards API docs and testing. Will optic supports python rest frameworks like fastapi, flask, etc..

Thanks you

**Comment by acunniffe** [comment]
Hey @Sharathmk99 -- it already does!

Just set your start command to the python project's start command. I believe fastapi / flask both use the `--port` flag to configure the port so you'd do something like this in your optic.yml file:

Then you can run `api start` to start the API with Optic monitoring the traffic. 

```
name: Your API
tasks:
  start:
    command: uvicorn app.main:app --host 0.0.0.0  --port $OPTIC_API_PORT
    baseUrl: 'http://localhost:3005'
```

If you need any more help feel free to setup a quick call: https://calendly.com/optic-onboarding/optic-support
