### ISSUE TITLE
Combining targetUrl and useTask makes the process hang indefinitely

### ISSUE THREAD

**Issue by aledalgrande** [opticdev/optic#881]
Hi, we run our test server inside the test runner, so it can share the same connection pool and see the data created during test transactions (they are rolled back after each test so never committed).

The issue is that, while trying to setup Optic, I realized that this setup makes the process hang:
```
name: "my project"
tasks:
  start:
    command: "rails s --port $PORT"
    inboundUrl: http://localhost:3000
  docs:
    targetUrl: http://localhost:7368
    inboundUrl: http://localhost:5000
  specs:
    useTask: docs
    command: bundle exec rspec spec/acceptance_optic
```

The tests hit `http://localhost:5000` while `http://localhost:7368` is the Rails server started by the test runner. When the test passes and the RSpec process exits, I have to stop the command with Ctrl-C, which obviously isn't ideal if I want to run on CI.

Do you have any workaround for this?

For reference, if I set `useTask: start` it works normally (but then my tests don't pass).

**Comment by LouManglass** [comment]
Howdy @aledalgrande ,

Normally when running in what we would call [dependent task mode](https://www.useoptic.com/docs/using/advanced-configuration#dependent-tasks) like your `specs` task, we'd expect that command process to exit gracefully which would bring down the Optic tasks. I understand that's not happening here, and your specific flow isn't one I've tried before. 

Is there any chance that this is an open-source project I can look at locally, or failing that, would you have time to [have a quick chat](https://calendly.com/d/pgv6-9tp7/30-minute-meeting) to show off your setup? I'd like to learn more. I'm sure we can find a workaround with a little digging.

**Comment by aledalgrande** [comment]
Thanks will try to setup a small repo to test out. If I run `api run docs` and then `bundle exec rspec spec/acceptance_optic` in a separate terminal it works without any issue.

**Comment by aledalgrande** [comment]
Here's a minimal repro: https://github.com/Latermedia/optic_task_issue

If you run `rspec` + `api run docs` in two separate terminals the test suite will pass and exit normally. But with `api run specs` it will get stuck.

**Comment by LouManglass** [comment]
Great, thanks! I'll dig into this a bit and see what our next steps are.

**Comment by notnmeyer** [comment]
@aledalgrande I think this is a bug related to `useTask`. Using the your example repo, try this optic.yml as a workaround,

```
name: "my project"
tasks:
  start:
    command: "rails s --port $PORT"
    inboundUrl: http://localhost:3000
  specs:
    targetUrl: http://localhost:7368
    inboundUrl: http://localhost:5000
    command: bundle exec rspec spec/acceptance
```
